### ISSUE TITLE
Reconstruct home header design

### ISSUE THREAD

**Issue by sagormajomder** [sagormajomder/coding-master#3]
Please move the header container styles from header component into home page component.
![Screenshot 2023-12-28 113226](https://github.com/sagormajomder/coding-master/assets/29459226/2c6e22be-34e3-406f-a5af-4189f1cbc785)

**Comment by susmitagain** [comment]
I created pull request for this issues. Please check

**Comment by sagormajomder** [comment]
The issue is solved. Thanks
